### ISSUE TITLE
'module' object has no attribute 'ExpressionStatement'

### ISSUE THREAD

**Issue by Faker0715** [najamnazar/designpatterndetection#1]
![image](https://user-images.githubusercontent.com/36560441/161364010-214bb074-2e37-4a10-aa24-32d8c865f234.png)
![image](https://user-images.githubusercontent.com/36560441/161364021-ee78b48a-9354-4d41-8c97-0bdc5a2ba453.png)
i don't solve it, can you help me?

**Comment by Faker0715** [comment]
![image](https://user-images.githubusercontent.com/36560441/161365520-3b01f6e0-d8a9-4849-9eb5-3f1aa9904ffe.png)

**Comment by najamnazar** [comment]
Install plyj manually from https://pypi.org/project/plyj/
